server:
  port: ${PORT}

spring:
  application:
    name: ${SERVICE_NAME}
  rabbitmq:
    host: rabbitmq
    port: 5672
    username: guest
    password: guest
    listener:
      simple:
        retry:
          enabled: true
          initial-interval: 1000
          max-attempts: 3

eureka:
  client:
    service-url:
      defaultZone: http://eureka-service:8761/eureka
      register-with-eureka: true
      fetch-registry: true
